### ISSUE TITLE
Make use of "overkillDamage" stat on the web side

### ISSUE THREAD

**Issue by SizzlingCalamari** [SizzlingStats/sizzlingstats.com#47]
A recent ss commit adds the "overkillDamage" stat which counts the amount of damage that was done to a player past their health on death. For example, if the victim's health before death was 3, and a 5 shot damage was fired at the victim, "overkillDamage" would be incremented by 2.

A total damage stat can be calculated by doing totalDmg = "damagedone" + "overkillDamage". This totalDmg value should be equal to the damage value that is displayed on logstf currently.

Implementation on the web server side is needed to take advantage of this stat.

https://github.com/SizzlingStats/sizzlingplugins/commit/0db12fd3b2a0bd979303283b91966270a11347ab

**Comment by forivall** [comment]
What should the terminology be? I'm thinking of changing "DPM" to total damage (since logs.tf uses total damage), and introducing "DDPM" as "damage dealt per minute" as the damage done stat. I'll also introduce a "FAQ" page to explain it.

**Comment by SizzlingCalamari** [comment]
Having two sets of similarly named damage numbers seems confusing to me. Even with the faq page, it might be an annoyance to people.

I was thinking "Real Damage", "Overkill Damage", "Total Damage".
So overall, having the columns "RD", "OD", "TD", "RDPM", "TDPM".
Thoughts?

**Comment by forivall** [comment]
I don't really think that displaying the overkill damage is specifically necessary. So just "RD", "TD", "RDPM" and "TDPM" would be enough.

**Comment by SizzlingCalamari** [comment]
Sounds good. If people do end up wanting overkill damage, then it's not too far away anyways.

**Comment by dy-dx** [comment]
@SizzlingCalamari I like the original acronyms that @forivall put in that pull request

**Comment by SizzlingCalamari** [comment]
I just don't like how saying casually saying damage or damage dealt could refer to either stat if the listener isn't aware that there are two damage stats. Saying real damage and total damage makes it more apparent that there is a differentiation between them.

**Comment by dy-dx** [comment]
I think
DMG should remain as what it was before
"total damage" should be named "overkill damage"
overkill damage should display "-" if it doesn't exist (old version stats)

this is the simplest in terms of implementation and it is the clearest to the user in my opinion

**Comment by SizzlingCalamari** [comment]
Having DMG remain the same is attractive, but "overkill damage" sounds more like a delta than a total to me. The idea is good, but I'm unsure about the naming.

For old stats, we could either keep the DMG column without the new total damage, or have both, but with the new total damage as "-" indicating that it doesn't exist. It's definitely more clear to the user to have both columns, but with the overkill damage as "-". It avoids the question of why don't stats from my server look the same as this other server (for outdated plugins). I think that's what we should do.

**Comment by forivall** [comment]
@dy-dx true, hiding columns in angular is pretty annoying

**Comment by SizzlingCalamari** [comment]
DMGO - "Damage with Overkill"
ODMG - "Overkill Damage"
ODPM - "Overkill Damage per Second"
DPMO - "Damage per Second with Overkill"

Can't think of much else, but the best we've come up with is either of these.

DMGO and DPMO or
ODMG and ODPM

**Comment by SizzlingCalamari** [comment]
ODMG - "Overkill Damage"
ODPM - "Overkill Damage per Second"

Let's finish this off.

**Comment by dy-dx** [comment]
Fixed by #50 .
